---
- name: add gpg key...
  become: yes
  become_user: root
  apt_key:
    url: '{{ varnish_apt_key_url }}'
    state: present
- name: add apt repo...
  become: yes
  become_user: root
  with_items: '{{ varnish_apt_repos }}'
  apt_repository:
    repo: '{{ item }}'
