---
- name: Add apt gpg key from {{ varnish_apt_key_url }}
  become: true
  become_user: root
  ansible.builtin.apt_key:
    url: '{{ varnish_apt_key_url }}'
    state: present
- name: Adding apt repos...
  become: true
  become_user: root
  with_items: '{{ varnish_apt_repos }}'
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
