---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: install os dep pkgs...
  become: true
  become_user: root
  with_items: '{{ varnish_os_pkgs|default([]) }}'
  package:
    name: '{{ item }}'
    state: present
- include_tasks: '{{ varnish_pkg_mgr }}.yml'
- name: install varnish
  become: true
  become_user: root
  package:
    name: varnish
    state: present
